import { SockServerResponse, SockServerResponseReload } from 'src/node/server/SockServer';

/**
 * A content to be convined with service_worker of development script generated by crx-monkey.
 * @param host SockServer host
 * @param sockPort SockServer port
 */
export function developSw(host: string, sockPort: number) {
  function startWebsocket25secLife() {
    const websocket = new WebSocket(`ws://${host}:${sockPort}`);

    websocket.addEventListener('message', ({ data }) => {
      const response = JSON.parse(data) as SockServerResponse<SockServerResponseReload>;

      if (response.type === 'reload') {
        switch (response.content.reloadType) {
          case 'RELOAD_CONTENT_SCRIPT':
          case 'RELOAD_SW':
          case 'RELOAD_CSS':
          case 'RELOAD_POPUP_JS':
          case 'RELOAD_POPUP_HTML':
          case 'ALL':
            chrome.runtime.reload();
            break;

          default:
            break;
        }
      }
    });
    setTimeout(() => {
      websocket.close();
    }, 25 * 1000);
  }

  // Keep a service_worker life.
  startWebsocket25secLife();
  setInterval(() => {
    startWebsocket25secLife();
  }, 25 * 1000);
}
